name: Run Regression Testing

on:
    workflow_dispatch:
        inputs:
            release:
                required:
                    true

jobs:
    run_regression_test:
        runs-on: ubuntu-latest

        # strategy:
        #     matrix:
        #         release: ["3.26.4","3.26.3","3.26.2","3.26.1","3.26.0","3.25.1","3.25.0","3.24.4","3.24.3","3.24.2","3.24.1","3.24.0","3.23.1","3.23.0","3.22.0","3.21.0","3.20.0"]
        #     fail-fast: false

        steps:
            -   uses: actions/checkout@v2

            -   name: Checkout Local Plugins
                uses: actions/checkout@v2
                with:
                    repository: beer-garden/example-plugins
                    path: ./regression_test/data/localplugins

            -   name: Run Regression Tests
                run: ./regression_test.sh ${{ github.event.inputs.release }}
                working-directory: ./regression_test

            -   name: Upload JMeter Results
                uses: actions/upload-artifact@v3
                with:
                  name: ${{ github.event.inputs.release }}-logs
                  path: ./regression_test/*.log
                  if-no-files-found: error


